### ISSUE TITLE
Add `crc_combine()`

### ISSUE THREAD

**Issue by TexZK** [marzooqy/anycrc#1]
Hi, I've been looking for this kind of library for some time. I was going to roll my own, but I see that you did almost all the job already!

Still, I see that there's no reference to the `crc_combine()` function yet.
Can you add it please? I think that would be useful.

Cheers

**Comment by marzooqy** [comment]
I think I could add it, but I wonder what practical uses it has.

**Comment by TexZK** [comment]
Thank you!

AFAIK it's mostly used for optimizations. For example, when dealing with multi-part messages, where each part has its own CRC, and the overall message has a cumulative CRC (of the same type). Parsers could skip data altogether in a first pass, focusing instead on the CRCs alone, to discard invalid messages in advance.

It happened to develop an in-house protocol with that kind of structure, where the CRCs were mandated by safety requirements.
Once each of the parts were known and validated independently, the overall CRC was simply the `crc_combine()` of the CRCs, also because the multi-parts were scrambled for safety and efficiency reasons.

**Comment by marzooqy** [comment]
I made a commit to add the combine method, though I haven't made a release yet.

**Comment by marzooqy** [comment]
The combine method is now included in the latest build.
